from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

driver=webdriver.Chrome(executable_path="C:\Drivers\chromedriver_win32\chromedriver.exe")
driver.get("https://www.rkkoushik.com/contact-us/")
driver.implicitly_wait(15)
driver.maximize_window()
driver.implicitly_wait(15)
loginBox = driver.find_element_by_xpath('//*[@id="form-field-name"]')
loginBox.send_keys("Hacker Your Site Hacked Please Pay Amount $20.25")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-field_1"]')
loginBox.send_keys("Rkkoushik35@gmail.com")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-email"]')
loginBox.send_keys("###")
nextButton = driver.find_elements_by_xpath('//*[@id="content"]/div/div/div/section[2]/div[2]/div/div[1]/div/div/div/div/form/div/div[5]/button')
nextButton[0].click()

driver.close()
driver=webdriver.Chrome(executable_path="C:\Drivers\chromedriver_win32\chromedriver.exe")
driver.get("https://www.rkkoushik.com/contact-us/")
driver.implicitly_wait(15)
driver.maximize_window()
driver.implicitly_wait(15)
loginBox = driver.find_element_by_xpath('//*[@id="form-field-name"]')
loginBox.send_keys("Hacker Your Site Hacked Please Pay Amount $20.25")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-field_1"]')
loginBox.send_keys("Rkkoushik35@gmail.com")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-email"]')
loginBox.send_keys("###")
nextButton = driver.find_elements_by_xpath('//*[@id="content"]/div/div/div/section[2]/div[2]/div/div[1]/div/div/div/div/form/div/div[5]/button')
nextButton[0].click()
time.sleep(15)
driver.close()
driver=webdriver.Chrome(executable_path="C:\Drivers\chromedriver_win32\chromedriver.exe")
driver.get("https://www.rkkoushik.com/contact-us/")
driver.implicitly_wait(15)
driver.maximize_window()
driver.implicitly_wait(15)
loginBox = driver.find_element_by_xpath('//*[@id="form-field-name"]')
loginBox.send_keys("Hacker Your Site Hacked Please Pay Amount $20.25")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-field_1"]')
loginBox.send_keys("Rkkoushik35@gmail.com")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-email"]')
loginBox.send_keys("###")
nextButton = driver.find_elements_by_xpath('//*[@id="content"]/div/div/div/section[2]/div[2]/div/div[1]/div/div/div/div/form/div/div[5]/button')
nextButton[0].click()
time.sleep(15)
driver.close()
driver=webdriver.Chrome(executable_path="C:\Drivers\chromedriver_win32\chromedriver.exe")
driver.get("https://www.rkkoushik.com/contact-us/")
driver.implicitly_wait(15)
driver.maximize_window()
driver.implicitly_wait(15)
loginBox = driver.find_element_by_xpath('//*[@id="form-field-name"]')
loginBox.send_keys("Hacker Your Site Hacked Please Pay Amount $20.25")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-field_1"]')
loginBox.send_keys("Rkkoushik35@gmail.com")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-email"]')
loginBox.send_keys("###")
nextButton = driver.find_elements_by_xpath('//*[@id="content"]/div/div/div/section[2]/div[2]/div/div[1]/div/div/div/div/form/div/div[5]/button')
nextButton[0].click()
time.sleep(15)
driver.close()
driver=webdriver.Chrome(executable_path="C:\Drivers\chromedriver_win32\chromedriver.exe")
driver.get("https://www.rkkoushik.com/contact-us/")
driver.implicitly_wait(15)
driver.maximize_window()
driver.implicitly_wait(15)
loginBox = driver.find_element_by_xpath('//*[@id="form-field-name"]')
loginBox.send_keys("Hacker Your Site Hacked Please Pay Amount $20.25")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-field_1"]')
loginBox.send_keys("Rkkoushik35@gmail.com")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-email"]')
loginBox.send_keys("###")
nextButton = driver.find_elements_by_xpath('//*[@id="content"]/div/div/div/section[2]/div[2]/div/div[1]/div/div/div/div/form/div/div[5]/button')
nextButton[0].click()
time.sleep(15)
driver.close()
driver=webdriver.Chrome(executable_path="C:\Drivers\chromedriver_win32\chromedriver.exe")
driver.get("https://www.rkkoushik.com/contact-us/")
driver.implicitly_wait(15)
driver.maximize_window()
driver.implicitly_wait(15)
loginBox = driver.find_element_by_xpath('//*[@id="form-field-name"]')
loginBox.send_keys("Hacker Your Site Hacked Please Pay Amount $20.25")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-field_1"]')
loginBox.send_keys("Rkkoushik35@gmail.com")
loginBox = driver.find_element_by_xpath('//*[@id="form-field-email"]')
loginBox.send_keys("###")
nextButton = driver.find_elements_by_xpath('//*[@id="content"]/div/div/div/section[2]/div[2]/div/div[1]/div/div/div/div/form/div/div[5]/button')
nextButton[0].click()
time.sleep(15)
driver.close()
